name: Build release image

# Add permissions block for GitHub Packages
permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'information'
        type: choice
        options:
          - information
          - debug
          - warning
          - critical
      tags:
        description: 'Purpose of Run This Workflow?'
        required: true
        type: string
  push:
    branches:
      - "main"
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
    pull_request:
    types: [opened, synchronize, reopened]
      
env:
  REGISTRY_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/squid-proxy
  GHCR_IMAGE: ghcr.io/${{ github.repository_owner }}/squid-proxy

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Print the purpose of run
        run: |
          echo "Purpose of Run: ${{ inputs.tags }}"

  # SonarQube Analysis Job
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=lferrarotti74_Squid-Proxy
            -Dsonar.organization=lferrarotti74
        
  # Build images on x86 runner
  build-x86:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [
          {name: "linux/amd64", tag: "amd64"},
          {name: "linux/386", tag: "i386"},
          {name: "linux/riscv64", tag: "riscv64"},
          {name: "linux/ppc64le", tag: "ppc64le"},
          {name: "linux/s390x", tag: "s390x"}
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set Environment
        uses: c-py/action-dotenv-to-setenv@v5
        id: source-env
        with:
          env-file: env/.env
          
      - name: Echo Squid Version from env file
        run: | 
          echo ${{ steps.source-env.outputs.squid_version }} >> "$GITHUB_ENV"
        
      - name: Prepare
        run: |
          platform=${{ matrix.platform.name }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> "$GITHUB_ENV"
        
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY_IMAGE }}
            ${{ env.GHCR_IMAGE }}
   
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up QEMU for Multi-Arch Builds
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: ${{ matrix.platform.name }}

      - name: Verify QEMU Installation
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          echo "QEMU has been set up successfully."

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1
        with:
          version: latest

      # Add caching for Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.platform.name }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.platform.name }}-
            ${{ runner.os }}-buildx-
        
      - name: Build and Push Image by Digest
        id: build
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          platforms: ${{ matrix.platform.name }}
          build-args: VERSION=${{ env.SQUID_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: mode=max
          sbom: true
          outputs: type=image,name=${{ env.GHCR_IMAGE }},push-by-digest=true,name-canonical=true,push=${{ github.event_name != 'pull_request' }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          
      # This is a workaround to prevent cache size from growing indefinitely
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
          
      - name: Export Digests
        if: github.event_name != 'pull_request'
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"
          echo "Digest file created:"
          ls -l /tmp/digests
          
      - name: Upload Digest
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  # Build images on ARM runner
  build-arm:
    runs-on: ubuntu-24.04-arm # ARM-specific runner
    strategy:
      matrix:
        platform: [
          {name: "linux/arm64/v8", tag: "arm64v8"},
          {name: "linux/arm/v7", tag: "arm32v7"},
          {name: "linux/arm/v6", tag: "arm32v6"}
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set Environment
        uses: c-py/action-dotenv-to-setenv@v5
        id: source-env
        with:
          env-file: env/.env
          
      - name: Echo Squid Version from env file
        run: | 
          echo ${{ steps.source-env.outputs.squid_version }} >> "$GITHUB_ENV"
        
      - name: Prepare
        run: |
          platform=${{ matrix.platform.name }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> "$GITHUB_ENV"
        
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY_IMAGE }}
            ${{ env.GHCR_IMAGE }}
   
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1
        with:
          version: latest

      # Add caching for Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-arm-buildx-${{ matrix.platform.name }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-arm-buildx-${{ matrix.platform.name }}-
            ${{ runner.os }}-arm-buildx-
        
      - name: Build and Push Image by Digest
        id: build
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          platforms: ${{ matrix.platform.name }}
          build-args: VERSION=${{ env.SQUID_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: mode=max
          sbom: true
          outputs: type=image,name=${{ env.GHCR_IMAGE }},push-by-digest=true,name-canonical=true,push=${{ github.event_name != 'pull_request' }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          
      # This is a workaround to prevent cache size from growing indefinitely
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
          
      - name: Export Digests
        if: github.event_name != 'pull_request'
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"
          echo "Digest file created:"
          ls -l /tmp/digests
          
      - name: Upload Digest
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    needs: 
      - build-x86
      - build-arm
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set Environment
        uses: c-py/action-dotenv-to-setenv@v5
        id: source-env
        with:
          env-file: env/.env
          
      - name: Echo Squid Version from env file
        run: | 
          echo ${{ steps.source-env.outputs.squid_version }} >> "$GITHUB_ENV"
      
      - name: Download digests
        uses: actions/download-artifact@v5
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true
          
      - name: List digests downloaded
        run: |
          echo "Digest files retrieved:"
          ls -l /tmp/digests
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY_IMAGE }}
            ${{ env.GHCR_IMAGE }}
          
      - name: Create manifest list and push to Docker Hub
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create --tag ${{ env.REGISTRY_IMAGE }}:latest \
            $(printf '${{ env.GHCR_IMAGE }}@sha256:%s ' *)
          docker buildx imagetools create --tag ${{ env.REGISTRY_IMAGE }}:${{ env.SQUID_VERSION }} \
            $(printf '${{ env.GHCR_IMAGE }}@sha256:%s ' *)

      - name: Create manifest list and push to GHCR
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create --tag ${{ env.GHCR_IMAGE }}:latest \
            $(printf '${{ env.GHCR_IMAGE }}@sha256:%s ' *)
          docker buildx imagetools create --tag ${{ env.GHCR_IMAGE }}:${{ env.SQUID_VERSION }} \
            $(printf '${{ env.GHCR_IMAGE }}@sha256:%s ' *)
            
      - name: Inspect image
        run: |
          echo "Docker Hub images:"
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:latest
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ env.SQUID_VERSION }}
          echo "GHCR images:"
          docker buildx imagetools inspect ${{ env.GHCR_IMAGE }}:latest
          docker buildx imagetools inspect ${{ env.GHCR_IMAGE }}:${{ env.SQUID_VERSION }}

  # Image security analysis
  analyze-image:
    runs-on: ubuntu-latest
    needs: merge
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Environment
        uses: c-py/action-dotenv-to-setenv@v5
        id: source-env
        with:
          env-file: env/.env
          
      - name: Echo Squid Version from env file
        run: | 
          echo ${{ steps.source-env.outputs.squid_version }} >> "$GITHUB_ENV"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.47.0

      - name: Scan Docker Hub latest image with Trivy
        run: |
          echo "Scanning ${{ env.REGISTRY_IMAGE }}:latest for vulnerabilities..."
          trivy image --exit-code 0 --severity HIGH,CRITICAL ${{ env.REGISTRY_IMAGE }}:latest
          
      - name: Scan Docker Hub versioned image with Trivy
        run: |
          echo "Scanning ${{ env.REGISTRY_IMAGE }}:${{ env.SQUID_VERSION }} for vulnerabilities..."
          trivy image --exit-code 0 --severity HIGH,CRITICAL ${{ env.REGISTRY_IMAGE }}:${{ env.SQUID_VERSION }}

      - name: Scan GHCR latest image with Trivy
        run: |
          echo "Scanning ${{ env.GHCR_IMAGE }}:latest for vulnerabilities..."
          trivy image --exit-code 0 --severity HIGH,CRITICAL ${{ env.GHCR_IMAGE }}:latest
          
      - name: Scan GHCR versioned image with Trivy
        run: |
          echo "Scanning ${{ env.GHCR_IMAGE }}:${{ env.SQUID_VERSION }} for vulnerabilities..."
          trivy image --exit-code 0 --severity HIGH,CRITICAL ${{ env.GHCR_IMAGE }}:${{ env.SQUID_VERSION }}

      - name: Generate Trivy vulnerability reports
        run: |
          mkdir -p trivy-reports
          trivy image --format json --output trivy-reports/docker-report-latest.json ${{ env.REGISTRY_IMAGE }}:latest
          trivy image --format json --output trivy-reports/docker-report-${{ env.SQUID_VERSION }}.json ${{ env.REGISTRY_IMAGE }}:${{ env.SQUID_VERSION }}
          trivy image --format json --output trivy-reports/ghcr-report-latest.json ${{ env.GHCR_IMAGE }}:latest
          trivy image --format json --output trivy-reports/ghcr-report-${{ env.SQUID_VERSION }}.json ${{ env.GHCR_IMAGE }}:${{ env.SQUID_VERSION }}
          
      - name: Upload vulnerability reports
        uses: actions/upload-artifact@v4
        with:
          name: trivy-vulnerability-reports
          path: trivy-reports
          retention-days: 14

      - name: Verify architecture support
        run: |
          echo "Verifying image architecture support..."
          manifest_latest=$(docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:latest --raw)
            
          # Define all expected architectures
          declare -A expected_archs
          expected_archs["linux/amd64"]="amd64,linux,"
          expected_archs["linux/386"]="386,linux,"
          expected_archs["linux/arm64"]="arm64,linux,"
          expected_archs["linux/arm/v7"]="arm,linux,v7"
          expected_archs["linux/arm/v6"]="arm,linux,v6"
          expected_archs["linux/riscv64"]="riscv64,linux,"
          expected_archs["linux/ppc64le"]="ppc64le,linux,"
          expected_archs["linux/s390x"]="s390x,linux,"
            
          # Check latest image
          echo "Checking architectures in :latest tag..."
          missing_archs=""
            
          # First, extract all valid platform entries from the manifest (excluding attestations)
          platforms=$(echo "$manifest_latest" | jq -c '.manifests[] | select(.platform.architecture != "unknown") | .platform')
            
          # Check each expected architecture
          for arch_name in "${!expected_archs[@]}"; do
            # Parse expected values
            IFS=',' read -r exp_arch exp_os exp_variant <<< "${expected_archs[$arch_name]}"
              
            # Initialize found flag
            arch_found=false
              
            # Check each platform in the manifest
            while read -r platform; do
              # Extract actual values
              act_arch=$(echo "$platform" | jq -r '.architecture')
              act_os=$(echo "$platform" | jq -r '.os')
              act_variant=$(echo "$platform" | jq -r '.variant // ""')
               
              # Compare values
              if [[ "$act_arch" == "$exp_arch" && "$act_os" == "$exp_os" ]]; then
                # For architectures with variants, check the variant too
                if [[ -n "$exp_variant" && "$exp_variant" != "" ]]; then
                  if [[ "$act_variant" == "$exp_variant" ]]; then
                    arch_found=true
                    break
                  fi
                else
                  # For architectures without variants, we already have a match
                  arch_found=true
                  break
                fi
              fi
            done < <(echo "$platforms")
              
            if [ "$arch_found" = true ]; then
              echo "✅ Found: $arch_name"
            else
              echo "⚠️ Missing: $arch_name"
              missing_archs="$missing_archs $arch_name"
            fi
          done
            
          # If we have missing architectures, print a warning but don't fail
          if [[ ! -z "$missing_archs" ]]; then
            echo "⚠️ Warning: The following architectures are not included in the image: $missing_archs"
            echo "This is not an error if these architectures were intentionally excluded."
          else
            echo "✅ All expected architectures are included in the image!"
          fi
