name: Docker Scout

# Add permissions block at the workflow level
permissions:
  contents: read
  packages: write
  pull-requests: write

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

env:
  REGISTRY: docker.io
  GHCR_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GHCR_IMAGE_NAME: ${{ github.repository_owner }}/squid-proxy
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}
  # Using `latest` as the tag to compare assuming that it's already pushed
  COMPARE_TAG: latest

jobs:
  build:
    # if: github.actor!= 'dependabot[bot]'   # ignore the pull request which comes from user dependabot.

    runs-on: ubuntu-latest
    # Job-level permissions are no longer needed as they're defined at workflow level
    # But you can keep them here if you want to override specific ones

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.SHA }}

      - name: Set Environment
        uses: c-py/action-dotenv-to-setenv@v5
        id: source-env
        with:
          env-file: env/.env

      - name: Echo Squid Version from env file
        run: | 
          echo ${{ steps.source-env.outputs.squid_version }} >> "$GITHUB_ENV" 

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3.10.0
        with:
          driver-opts: |
            image=moby/buildkit:v0.10.6

      # Login to Docker Hub
      - name: Log into Docker Hub registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_IMAGE_NAME }}
          labels: |
            org.opencontainers.image.revision=${{ env.SHA }}
          tags: |
            type=edge,branch=$repo.default_branch
            type=semver,pattern=v{{version}}
            type=sha,prefix=,suffix=,format=short

      # Set lower case image name for both registries
      - name: Set lower case owner names
        run: |
          echo "DOCKERHUB_IMAGE_LC=${DOCKER_IMAGE,,}" >>${GITHUB_ENV}
          echo "GHCR_IMAGE_LC=${GHCR_IMAGE,,}" >>${GITHUB_ENV}
        env:
          DOCKER_IMAGE: '${{ github.repository }}'
          GHCR_IMAGE: 'ghcr.io/${{ github.repository_owner }}/squid-proxy'

      # Build and push Docker image with Buildx (don't push on PR)
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6.16.0
        with:
          context: .
          build-args: VERSION=${{ env.SQUID_VERSION }}
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Use GHCR for cache to avoid Docker Hub rate limits
          cache-from: |
            type=registry,ref=${{ env.GHCR_REGISTRY }}/${{ env.GHCR_IMAGE_LC }}:buildcache
            type=registry,ref=${{ env.REGISTRY }}/${{ env.DOCKERHUB_IMAGE_LC }}:buildcache
          cache-to: type=registry,ref=${{ env.GHCR_REGISTRY }}/${{ env.GHCR_IMAGE_LC }}:buildcache,mode=max

      - name: Docker Scout
        id: docker-scout
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations,compare
          image: ${{ steps.meta.outputs.tags }}
          # Try GHCR first for comparison to avoid rate limits
          to: ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_IMAGE_NAME }}:${{ env.COMPARE_TAG }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.COMPARE_TAG }}
          ignore-base: true
          ignore-unchanged: true
          only-severities: critical,high,medium
          only-fixed: true
          write-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }} # to be able to write the comment